apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: microservice-a
  description: description
  annotations:
    backstage.io/techdocs-ref: dir:../ 
    kafka.apache.org/consumer-groups: sample-consumer-a

spec:
  type: service
  lifecycle: production
  owner: admin
  system: system-a
  providesApis:
    - PROD_SAMPLE_GRPC_API_V1
    - PROD_SAMPLE_REST_API_V1
    - PROD_SAMPLE_GRAPHQL_API_V1
    - PROD_SAMPLE_ASYNC_API_V1    
    - EXPERIMENTAL_SAMPLE_GRPC_API_V1
    - EXPERIMENTAL_SAMPLE_REST_API_V1
    - EXPERIMENTAL_SAMPLE_GRAPHQL_API_V1
    - EXPERIMENTAL_SAMPLE_ASYNC_API_V1
  dependencyOf:
    - component:default/microservice-b

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: microservice-b
  description: description    
spec:
  type: service
  lifecycle: production
  owner: admin
  system: system-b
  consumesApis:
    - PROD_SAMPLE_GRPC_API_V1
    - PROD_SAMPLE_REST_API_V1
    - PROD_SAMPLE_GRAPHQL_API_V1
    - PROD_SAMPLE_ASYNC_API_V1
    - EXPERIMENTAL_SAMPLE_GRPC_API_V1
    - EXPERIMENTAL_SAMPLE_REST_API_V1
    - EXPERIMENTAL_SAMPLE_GRAPHQL_API_V1
    - EXPERIMENTAL_SAMPLE_ASYNC_API_V1
  dependencyOn:
    - component:default/microservice-a
